### ISSUE TITLE
Lags on opening

### ISSUE THREAD

**Issue by Jimbo138** [Silverfeelin/Starbound-SpawnableItemPack#20]
I noticed on my old computer that whenever I opened the Spawnable Items window, my game would lag, presumably because it was having a hard time loading all the items. Maybe you should add an option to either have no items load on opening until the user searches for something or opens a category, or have the user set which category they want it to open on startup by default.

**Comment by Silverfeelin** [comment]
I'm making the mod remember your selected search text, category and ([soon to be added](https://github.com/Silverfeelin/Starbound-SpawnableItemPack/issues/21)) rarity filter.
This should cut down load times, since it doesn't have to add all items to the list (assuming you've previously selected something mentioned above).

**Comment by Silverfeelin** [comment]
Some improvements have been made in https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v1.3.2.2.
