### ISSUE TITLE
Item Rarity Filter

### ISSUE THREAD

**Issue by TUF1nish3d** [Silverfeelin/Starbound-SpawnableItemPack#21]
Maybe you could add an item rarity order from either common to most rare, or something like that I kind of get confused of when the items don't seem to be in order like that for me.

**Comment by Silverfeelin** [comment]
The interface already takes a long (relatively speaking) time to load because of the number of items. Sorting this collection by rarity would take multiple iterations over all items, which could increase load times by a bit more. Definitely possible though. I might look into a setting for this if I get the time.

An additional feature would be to search by rarity, like the old (and maybe also new? I don't remember) vanilla crafting interfaces.

**Comment by Silverfeelin** [comment]
I'm considering replacing the unused pages part of the interface with rarity options. You could select any of the 5 rarities. Items matching any selected rarity will be shown.

*Progress report:*
![](http://i.imgur.com/9ha9WFr.png)

**Comment by Silverfeelin** [comment]
Included in https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v1.3.2.2.
