### ISSUE TITLE
suggestion: hook into tabula rasa

### ISSUE THREAD

**Issue by InkDragon** [Silverfeelin/Starbound-SpawnableItemPack#28]
if possible I would like to suggest hooking into tabula rasa enabled mods and automatically add their items  to the list of spawnables

**Comment by Silverfeelin** [comment]
The Tabula Rasa is a generic crafting station that follows the same rules as vanilla crafting stations; they display items based on valid recipes (recipes matching the filter set by the crafting station). Recipes are loaded by the game and there's no way for me to fetch a list of existing recipes in-game. You can look up what recipes are available to create a known item, but that's not really useful here since we don't know the item.

It's a nice suggestion, but sadly this does not seem to be possible (in Starbound 1.3.3). If Starbound 1.4 features new API functions that can help, I might re-open this issue.
