### ISSUE TITLE
SIP does not shows up in Bounty Hunter Update

### ISSUE THREAD

**Issue by ElementalCyclone** [Silverfeelin/Starbound-SpawnableItemPack#34]
**Problem** : 
 Spawnable Item Pack does not shows up at all in QuickBar options, nor scrolling shows it.

**Environment** : 

- Windows 10 64-bit

- a fresh install of Starbound Bounty Hunter Update, Non-STEAM

- Most recent version of StardustLib

- Most recent version of Spawnable Item Pack

(Attempted) **Reproduction** : 

1. Fresh install base game

2. Install required MOD

3. Launch game, then create new character with "Skip Tutorial" checked

4. Start created character

5. After game loaded, click on Quickbar, no SIP option shown

6. Give player admin privilege, repeat step 5, same result

7. Exit

Log for the said attempt [starbound.log](https://github.com/Silverfeelin/Starbound-SpawnableItemPack/files/4447784/starbound.log)

In the log, there's a line that worth to mention, it said
`[05:22:57.603] [Error] Could not apply patch from file /quickbar/icons.json.patch in source: ..\mods\733665104.pak.  Caused by: (JsonPatchException) Could not apply patch to base. (JsonPatchException) Could not apply operation to base. (TraversalException) No such key 'items' in pathApply("/items/silverfeelin:spawnableItemPack")`

**Comment by Silverfeelin** [comment]
`(TraversalException) No such key 'items' in pathApply("/items/silverfeelin:spawnableItemPack")`

This indicates the quickbar file is outdated or corrupt. The format of said file hasn't changed in a _very_ long time.
https://github.com/Silverfeelin/Starbound-Quickbar-Mini/blob/master/quickbar/icons.json
Note the last change: May 5th, 2019.

So either you have a really old version of the Quickbar or some other mod is corrupting the file by removing the "items" table from that file before SIP is loaded and gets to apply the patch.

As I can't tell what's the root cause of this issue I suggest you first try to update the Quickbar. If that doesn't work, try finding what other mod is causing the conflict. Launching the game with just the Quickbar and SIP should work just fine.

**Comment by ElementalCyclone** [comment]
As i mentioned before, the only Mod i use when asking this question are SIP and StardustLib, this also stated in the log file.

But i also tested SIP w/ Quickbar Mini instead of StardustLib, it (the SIP) works. The thing is, SIP and Quickbar Mini last update were Q2/Q3 2019, while StardustLib last update was 23 March 2020 (as per Steam Workshop page).

So, maybe something from newly updated StardustLib breaks quickbar stuffs ?
should i bring this to StarTech GitHub issue too ?

**Comment by ElementalCyclone** [comment]
I think i've found the problem. It is the StardustLib's format that indeed outdated.
Found this after unpacked the installed StardustLib .pak file in my installation. For now i'll close the issue and bring this to StarTech git's.

Thank you.

**Comment by Silverfeelin** [comment]
@ElementalCyclone Where did you get your StardustLib file? I just downloaded the last release from GitHub; it uses the newer format. I also subscribed to StardustLib on Steam; it uses the newer format.

**Comment by ElementalCyclone** [comment]
I got it from not quite Steam Workshop, i mean use 3rd party tool to download the mod's release file from Steam Workshop
