### ISSUE TITLE
[SUGGESTION] Spawnable Items menu button only shows for admin players

### ISSUE THREAD

**Issue by Archilyte** [Silverfeelin/Starbound-SpawnableItemPack#35]
Just a neat suggestion.
Might be useful for servers
(I just want /admin to toggle the option)

**Comment by Silverfeelin** [comment]
This will not become a default option as many players that shouldn't have admin powers on servers use (and are allowed to use) it on servers. Because player files are client-sided people can and always will cheat whether they can use this mod or not. Even with the change, these players could just enter singleplayer, use `/admin`, get items, then join a server. It just ends up making this mod less useful, without achieving what you're trying to achieve.

That said, you could always patch the `/quickbar/icons.json` file in a separate mod to add the `admin` condition to the Spawnable Item Pack entry. Then, if servers really want this mod blocked, they could add the patch to a modpack. The modpack can be made required by disallowing asset mismatches in the server config.
